print("*********You have reached a checkpoint*******")
x=1
a=2
b=3
c=4
while True:
  print("You are in the wallway trying to find a way out but the only thing that you do is just walk")
  input()
  print(a,"- Do this wallway have an exit?")
  input()
  print(x,"- I'm worried about how this is going to end")
  input()
  print(b,"- Don't worry about it, everything is going to be finEEEEEEEEEE")   
  input()
  input()
  print(a,"-",b,"where are you??!!")
  input()
  print(b,"- Where are you?! You sound above me")
  input()
  print("You can't see where",b,"is, would you dare to jump?")
  input()
  g=input("a) Yes. b) No wth")

 if (g=="a"):
    print(x,"- Hi God, it's me again *jump*")
    input()
    print("You stomp onto a bed")
    input(x,"- This isn't that bad")
    input()
    print(b,"- Why you stomp onto the bed? I just broke my back fallen onto the floor")
    input()
    print(c,"Are you guys in well conditions of life or do you want to commit a suicide due to the amount of depression that puberty has caused to you? Petit question")
    input()
    print(x,"- Yup")
    input()
    print(x,"- Guys do you want to jump down here?")
    input()    
    print("Do you think",a,"and",c,"would dare to jump?")
    input()
    print("a)Yes")
    print("b)No")    
    print("c)Not both, but maybe",a)
    print("d)Not both, but maybe",c)
   
    if (ñ=="a"):
     input()  
     print(c,"- Okay guys, here we come...")
     input()
     print("Both fall down and they see you")
     input()
     print(a,"- Okay guys, we need to make this quick, i have a date and i don't know what time is it")
     input()
     print(b,"- Geez! Sorry")
     input()
     print(x,"- Someone turn on the lights or something")
     input()
     print(a,"find a switch and turns the lights on")
     input()
     print(c,"- Look! There are a lot of pictures and frames on the wall.")
     input()
     print("What should you do first?")
     print("a)Look under the suspicious bed")
     print("b) Take a look to the strange pictures")
     print("c) Look around in the corners")
     3=input("")
      if(3=="a"):
       input()
       print("You look under the bed, and see spiderwebs and a piece of paper taped there")
       input()
       print(x,"- ummm i found a paper, i think it says something")
       input()
       print(a,"- Spit it, what does it say?")
       input()
       print(x,"- It says: Good luck to escape from here if you all fell in this room, you won´t find another clue here.")
       input()
       input()
       print("Sh*t")
       input()
       print("Game over....")
       break