print("Hi! Ready to answer this?")
name=input("What's your name? ")
print("Greetings,", name)
city=input("Where are you from? ")
print(city,"? That sounds interesting!")
read=input("Do you read? ")
print(read,"?, I see")
song=input("What's your favorite song at this moment? ")
print("Wow! Im going to listen to",song,"to see if i like it!")
color=input("What is your favorite color? ")
print(color,"? That's a nice color",name)
age=input("I forgot! How old are you? ")
print(age,"is a great age.")
movie=input("What movie do you like the most? ")
print("I like",movie,"too")
sport=input("What is your favorite sport? ")
print(sport,"?",name,"? Wow! Thats surprising")
zodiac=input("What is your zodiac sign? ")
print("I suppsed you are a",zodiac)
day=input("So you were born on the? ")
print("Oh i see...",day)
print("It was nice to talk to you :) see ya soon")